### ISSUE TITLE
Expecting error on String.proto.startsWith (et al), but not getting one

### ISSUE THREAD

**Issue by remy** [amilajack/eslint-plugin-compat#119]
This is the simplified test case: https://gist.github.com/4cbb0bc3efe5ca0efb6977b570de7f46

When I run eslint on this code, I'm expecting that `startsWith` should fail as it's not available in IE11 (which AFAIK is included in the default browser selection), but it doesn't. I'm unsure if I'm missing something basic.

Any ideas?

**Comment by kenju** [comment]
@remy 

Thanks for reporting with reproducible code.

I suppose, if you want to add a new rule, currently it is supposed to add a new rule at `providers/CanIUseProvider.js` with a test.

Here is an example 👉 https://github.com/amilajack/eslint-plugin-compat/pull/115

**Comment by kenju** [comment]
I look into caniuse-db, but `String.prototypes.startsWith` does not seem to be supported yet (currently eslint-plugin-compat is using the caniuse-db as a data-srouce)

https://github.com/Fyrd/caniuse/search?q=startsWith&type=Code

Maybe this gonna be fixed by this (e.g. https://github.com/amilajack/eslint-plugin-compat/issues/104)

**Comment by remy** [comment]
Oh sod, of course. Yeah, that makes sense that caniuse doesn't list the support and actually redirects off to kangax compat table.

I'll close this and track #104, cheers!
