### ISSUE TITLE
Remove unused files from npm package

### ISSUE THREAD

**Issue by amilajack** [amilajack/eslint-plugin-compat#3]
This can be done with a build step which removes every file that isnt included in the rules.

**Comment by ljharb** [comment]
What files do you think are worth excluding? Being able to do `npm explore foo && npm install && npm test` is very valuable, as is being able to explore a module you've previously installed while offline.

As a rule, I include all docs, tests, and original source files in every package I publish - which tends to leave the files to exclude as CI-specific configs and github templates - which aren't very significant in size.

At any rate I think this would be best done with an `.npmignore` rather than a build step, so that it's explicit and git-explorable rather than dynamic and only really verifiable after publish.

**Comment by amilajack** [comment]
Does that mean that that tests have to be included as `dependencies`? Wont that slow down installs? We're using a significant amount devDeps. Thoughts on this?

**Comment by ljharb** [comment]
Oh no - I still leave dev stuff in devDeps (that's what `npm install` is for in my above command).

**Comment by Munter** [comment]
What unused files are in the npm packages? The `files`-section of package.json seems pretty well crafted for only including the source code: https://github.com/amilajack/eslint-plugin-compat/blob/master/package.json#L24-L27

I guess the whitelist of the non-existing `/index.js` could be removed, but it's not adding anything to the released package

**Comment by ljharb** [comment]
`files` is dangerous - it's far too easy to add a new file to the repo but forget to add it to the whitelist.

If you *do* want to restrict what gets published (I discourage that too), then please only ever use `.npmignore`.

**Comment by Asudhaishao** [comment]
顶一个

**Comment by ljharb** [comment]
@Asudhaishao thumbs ups should be added as emoji reactions, not posts, to avoid cluttering threads. I'll delete your post and then this one; please feel free to add a 👍 emoji to whichever posts you like!

**Comment by jaydenseric** [comment]
It's a best practice to publish as little as possible. If everyone published their tests, snapshots, screenshots, etc. node_modules would be gigabytes of stuff is not useful to a consumer.

Use a whitelist with the package.json `files` field (which appears to already be in place here). You can include a dir, such as `lib` or `dist` if everything you want to publish is in there, which reduces human error and makes for a short whitelist. Don't whitelist things such as `readme.md` that are in the list of files npm forcibly includes. I like that people notice as soon as a whitelist is incorrect and the package stops working; it forces quality. A blacklist is far less elegant to maintain properly, it's long and everyone forgets to update it.

You can test what is included by running `npm pack` in the repo, and extracting the archive.

Few other suggestions:

- Use the package.json `prepare` script for your build script, that way people can install and test the project as a git dependency (`npm install amilajack/eslint-plugin-compat#<commit> --save-dev`).
- Include all sorts of checks such as linting in the `test` script. That way it's a one stop shop for CI, etc.
- Use a `prepublishOnly` script: `npm run prepare && npm test`.
- [npm-run-all](https://github.com/mysticatea/npm-run-all) is handy to manage subtasks for the above scripts.

**Comment by ljharb** [comment]
@jaydenseric mot people do publish all those things, and it’s not that large - and I’ve explained already that they are useful to some consumers.

Again, files is dangerous and should never be used - if you want to exclude files, use npmignore.

As for npm pack, if you can provide an ergonomic way to test that in ci, I’ll be happy to do it, but I’ve not yet found one.

**Comment by jaydenseric** [comment]
@ljharb 

[Facebook considers `files` safe enough to use for `react`](https://github.com/facebook/react/blob/v16.4.1/packages/react/package.json#L11).

Agreed there is a risk something important could be ignored from publishing when whitelisting, but there is still a risk when blacklisting. Really, the industry status quo with testing is flawed on so many levels:

- Popular testing frameworks like AVA and Jest attempt to do their own transpilation of source, instead of testing the actual distribution files that get published.
- People often import and test functions from where they are located in source, instead of testing how they are exposed in the published API.
- Tests are often run with devDependencies present, that are not present when a consumer installs the package causing a lot of dependencies/peer dependency issues to slip through.
- As you pointed out, no tools run tests on the what the final contents of the published package are. Errors when blacklisting ***or*** whitelisting go unnoticed.
- Tests are often only run in a CJS environment. All tests should be run a second time using native ESM imports of the exposed API (with Node.js in `--experimental-modules` mode, until the feature on by default).

**Comment by ljharb** [comment]
"X company does it" is not a justification.

There is no risk of breakage when blacklisting, which is the important part.
 > instead of testing the actual distribution files that get published.
> instead of testing how they are exposed in the published API.

all true - so file an issue on those projects.

> Tests are often run with devDependencies present

that's what eslint-plugin-import is for - it ensures that any dep in non-tests is in "dependencies". This is a solved problem.

> Errors when whitelisting or blacklisting go unnoticed.

Indeed - but errors when blacklisting are non-problems.

> Tests are often only run in a CJS environment.

CJS is the only environment that exists, until node ships an unflagged modules implementation (I'm in the modules working group for node; the implementation is subject to change, and is not worth testing against just yet).

I'm going to close this. A PR that adds an `.npmignore` will be considered, but both tests and raw source should be published, so there won't be much value.

**Comment by jaydenseric** [comment]
My last side comment, I promise 🙏

> "X company does it" is not a justification.

Agreed, I only brought it up to point out that your view that whitelisting files is unacceptably risky is a (minority?) opinion, not to be accepted on authority alone.

> There is no risk of breakage when blacklisting, which is the important part.

That's not true. Blacklists are written by humans, so it is entirely possible to accidentally blacklist `lib` or `dist` or some sort of JSON file or something that is required, and tests will still pass. It is debatably **less** risky that whitelisting, but not with zero risk.

> that's what eslint-plugin-import is for - it ensures that any dep in non-tests is in "dependencies". This is a solved problem.

While linting is be a big part of a solution to that particular issue, many packages either do not have it configured ([eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import) has only half the downloads of [eslint](https://www.npmjs.com/package/eslint)), or do not include linting in their main`test` script.

> CJS is the only environment that exists

That's not true, thousands of people are using the `--experimental-modules` flag. Some (including me) in production. I'm shipping `.mjs` in all my packages, and if packages like [`graphql` are doing it](https://github.com/graphql/graphql-js/blob/v14.0.0-rc.2/package.json#L41) too we might as well work out best practices for testing it. Whatever the final Node.js API for native ESM looks like (it might not change that much), we will want to test it.

Regardless of native ESM, compilers such as Webpack that give ESM special treatment. Thurough testing would check everything works ok once webpack uses the `module` entrypoint and does its resolving (it resolves .mjs before .js, like Node.js) and optimizations.

A lot of the status quo flaws are not getting better on their own over time (`jest` is getting more, not less popular, event though alternatives such as `tap` exist) and some of the best practices such as linting imports and dependencies are not everywhere in the wild. There are no solutions for some of the other issues to do with verifying the exposed API and published files. Really, there is an opportunity for a new tool to reinvent testing packages.
